### ISSUE TITLE
Custom Block Tracers

### ISSUE THREAD

**Issue by MysteryTimeTrav** [APDevTeam/Movecraft-Combat#103]
Ability to change the type of blocks used as block tracers.

Example: Cobwebs to Dead_Brain_Coral[waterlogged=false] and Glowstone to Shroomlight

**Comment by TylerS1066** [comment]
I think it's a really good idea to allow these materials to be configurable, but unfortunately Movecraft doesn't have the ability to configure block data in that way yet.

A good first step will be to add material configuration to tracers tho.
