### ISSUE TITLE
Particle Tracers Delay Problem

### ISSUE THREAD

**Issue by MysteryTimeTrav** [APDevTeam/Movecraft-Combat#104]
The effect given to the particle tracers is delayed by about 20 ticks after the explosion actually occurs

Suggestion would be to have it appear as soon as the explosion occurs with no delay if possible so particle tracers could be used as a way to see the effects of cannons further out

[https://github.com/APDevTeam/Movecraft-Combat/blob/e1f391c1078d919d745f1264c1c6d61a85380c2b/src/main/java/net/countercraft/movecraft/combat/features/tracers/TNTTracers.java#L157](https://github.com/APDevTeam/Movecraft-Combat/blob/e1f391c1078d919d745f1264c1c6d61a85380c2b/src/main/java/net/countercraft/movecraft/combat/features/tracers/TNTTracers.java#L157)

**Comment by TylerS1066** [comment]
The reason I added that delay was so the particles can show up after the explosion has cleared.

**Comment by MysteryTimeTrav** [comment]
The problem is that you wouldn't see the explosion past a certain distance anyway as while Minecraft renders TNT entities out to that range, it doesn't render the particles of the explosion

this means that the tracer particle explosion indicator appears awkwardly late after a crater does

Movecraft-Combat already has a setting to disable the explosion indicator within a certain radius which would allow for protection against redundancy if the explosion occurs within normal Minecraft particle rendering
`TracerMinDistance: 15 # Minimum distance at which glowstone tracers are spawned on explosion`

But if this delay is necessary in certain cases and uses of the particle tracers, would it be possible for a config setting to be added to adjust the delay?

**Comment by TylerS1066** [comment]
Adding a config for the delay should be simple

**Comment by MysteryTimeTrav** [comment]
Something I also noticed is that sometimes the impact particles don't show up but the tracers do. Is there a limit to how many can spawn? I'm not sure if this is the case because sometimes they don't appear even when dealing with pretty small amounts of TNT.

**Comment by goodroach** [comment]
https://github.com/APDevTeam/Movecraft-Combat/blob/e1f391c1078d919d745f1264c1c6d61a85380c2b/src/main/java/net/countercraft/movecraft/combat/features/tracers/TNTTracers.java#LL164C1-L164C1

This is the line yes? All I have to do is just add a setting option for it?

**Comment by TylerS1066** [comment]
Yup
