### ISSUE TITLE
Some blocks' blast resistance can't be changed

### ISSUE THREAD

**Issue by goodroach** [APDevTeam/Movecraft-Combat#111]
**Description**
There currently seems to be a bug with the blast resistance override portion of the plugin where it can't seem to change the blast resistance of certain blocks. I know of one such block, blackstone stairs. For some reason, blackstone stairs cannot have their blast resistance changed at all. Do you know why this might happen? I investigated this for a while now but I can't figure out why. Here's the config:

BlastResistanceOverride:
  blackstone_stairs: 9 #This does not work.
  iron_block: 9 #This does work, and has the same effect as endstone.

**Comment by TylerS1066** [comment]
I have no idea why this might occur.  I'll have to try testing it out and see if I can replicate the issue.
