### ISSUE TITLE
Togglable Bleedfix

### ISSUE THREAD

**Issue by goodroach** [APDevTeam/Movecraft-Combat#118]
Bleedfix is currently baked into durability override and while that is convenient for some, it's troublesome for others because it's two features in one when it could just be an option to toggle it on using a simple config option like 'enableBleedFix: true'

**Comment by TylerS1066** [comment]
To clarify, "bleedfix" is the functionality at [DurabilityOverride.java line 58-61](https://github.com/APDevTeam/Movecraft-Combat/blob/main/src/main/java/net/countercraft/movecraft/combat/features/DurabilityOverride.java#L58).

I think an ideal solution would be to move the feature to a separate class from Durability Override and implement the config as you mention.
