### ISSUE TITLE
Paper 1.21

### ISSUE THREAD

**Issue by Nikkilectric** [APDevTeam/Movecraft-Combat#125]
Currently, Movecraft combat does not run on paper 1.20.6

**Comment by TitanHammer** [comment]
this is the same for the most recent experimental movecraft build for 1.20.6 as it also isnt able to function on paper 1.20.6. the plugin loads, but im unable to pilot anything

**Comment by Nikkilectric** [comment]
UPDATED: Plugin currently does not function on 1.21
